return {
    blueprint = import('./modeling/blueprint.lua'),
    BoundingBox = import('./space/BoundingBox.lua'),
    Bridge = import('./space/Bridge.lua'),
    commands = import('./commands.lua'),
    Coord = import('./space/Coord.lua'),
    curves = import('./curves.lua'),
    facingTools = import('./space/facingTools.lua'),
    Farm = import('./planner/Farm.lua'),
    highLevelCommands = import('./highLevelCommands.lua'),
    Location = import('./Location.lua'),
    Mill = import('./planner/Mill.lua'),
    navigate = import('./navigate.lua'),
    Position = import('./space/Position.lua'),
    Project = import('./planner/Project.lua'),
    Sketch = import('./modeling/Sketch.lua'),
    state = import('./state.lua'),
    Plan = import('./planner/Plan.lua'),
}
